name: SonarCloud Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud_analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install Server Dependencies
        run: npm install
        working-directory: gluGuideSetup/server

      - name: Install Client Dependencies
        run: npm install
        working-directory: gluGuideSetup/client

      - name: Install Vitest Coverage Dependencies
        run: npm install -D @vitest/coverage-v8
        working-directory: gluGuideSetup/client

      - name: Run Client Tests with Coverage
        run: npx vitest run --coverage
        working-directory: gluGuideSetup/client

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}